server:
  port: 6080

management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: health,info,prometheus,metrics

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    user: admin
    password: passw0rd

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/skellig-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: skellig
    password: skellig

  cassandra:
    keyspace-name: skellig
    contact-points: localhost
    schema-action: CREATE_IF_NOT_EXISTS
    port: 9042
