version: '3'
services:
  ibmmq:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: skellig-demo-ibmmq-host
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=admin
    container_name: skellig-demo-ibmmq
    user: mqm
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: skellig-demo-rmq
    hostname: skellig-demo-rmq-hst
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  mysql:
    image: mysql:5.7
    container_name: skellig-demo-mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./skellig-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skellig-db
      MYSQL_USER: skellig
      MYSQL_PASSWORD: skellig
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  cassandra:
    image: cassandra:3.11.2
    container_name: skellig-demo-cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - "./skellig-cassandra-init.sh:/skellig-cassandra-init.sh"
    command: "sh /skellig-cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
#    volumes:
#      - ./skellig-cassandra.cql:/docker-entrypoint-initdb.d/init.sql
    restart: always